<?xml version="1.0"?>
<robot name="lidar_cart" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Includes -->
  <xacro:include filename="$(find lidar_cart)/urdf/lidar.xacro"/>
  <xacro:include filename="$(find lidar_cart)/urdf/gazebo_control.xacro"/>

  <!-- Properties -->
  <xacro:property name="chassis_length" value="0.3"/>
  <xacro:property name="chassis_width" value="0.2"/>
  <xacro:property name="chassis_height" value="0.1"/>
  <xacro:property name="caster_wheel_radius" value="0.03"/>
  <xacro:property name="wheel_radius" value="0.1"/>
  <xacro:property name="wheel_width" value="0.01"/>
  <xacro:property name="wheel_separation" value="0.22"/> <!-- chassis_width + wheel_width -->

  <!-- Base Footprint -->
  <link name="base_footprint"/>

  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <!-- Base Link -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
      <origin xyz="0 0 ${chassis_height/2}" rpy="0 0 0"/>
      <material name="gray">
        <color rgba="0.5 0.5 0.5 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
      <origin xyz="0 0 ${chassis_height/2}" rpy="0 0 0"/>
    </collision>
    <inertial>
      <mass value="1.0"/>
      <origin xyz="0 0 ${chassis_height/2}"/>
      <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
    </inertial>
  </link>

  <!-- Wheels Macro -->
  <xacro:macro name="wheel" params="prefix y_offset">
    <link name="${prefix}_wheel">
      <visual>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="black">
          <color rgba="0 0 0 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.5"/>
        <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
      </inertial>
    </link>

    <joint name="${prefix}_wheel_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${prefix}_wheel"/>
      <origin xyz="0 ${y_offset} ${wheel_radius}" rpy="${-pi/2} 0 0"/> 
      <!-- wheel radius offset is handled by base_footprint -> base_link, so here z=0 relative to base_link bottom? 
           Wait, base_link origin is at bottom. Wheel center should be at z = 0 relative to base_link if base_link bottom is at 0.
           However, base_link visual is shifted up by height/2 via origin.
           Actually simple setup:
           base_footprint -> base_link (z=wheel_radius).
           So base_link origin is center of wheels Z-wise.
      -->
      <!-- Let's correct visual origin of base_link. 
           base_link origin is where? Usually center of rotation.
           Let's say base_link origin is center of rear axle projected to ground? 
           Here I did base_footprint at ground. base_link at axle height.
           So wheels should be at z=0 relative to base_link.
      -->
      <axis xyz="0 0 1"/>
    </joint>
  </xacro:macro>
  
  <!-- Let's fix wheel origin. -->
  <!-- Redefine wheel joint origin. 
       The wheel cylinder is oriented along Z (default cylinder). rotated -pi/2 around X makes it axis along Y.
       The origin is center of wheel.
       base_link origin is at height wheel_radius from ground.
       So wheel origin relative to base_link is 0 0 0?
       Yes.
  -->

  <xacro:wheel prefix="left" y_offset="${wheel_separation/2}"/>
  <xacro:wheel prefix="right" y_offset="${-wheel_separation/2}"/>

  <!-- Caster Wheel -->
  <link name="caster_wheel">
    <visual>
      <geometry>
        <sphere radius="${caster_wheel_radius}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <sphere radius="${caster_wheel_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.1"/>
      <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
    </inertial>
  </link>

  <joint name="caster_joint" type="fixed">
    <parent link="base_link"/>
    <child link="caster_wheel"/>
    <origin xyz="${chassis_length/2 - 0.05} 0 ${caster_wheel_radius}" rpy="0 0 0"/>
    <dynamics damping="0.0" friction="0.0"/>
  </joint>
  
  <!-- Add friction to caster so it slides? Or simple sphere.
       Gazebo specific friction for caster to allow sliding or continuous joint.
       For simple cart, fixed sphere with low friction is okay-ish for simulation, 
       but strictly it should ideally be a caster joint. 
       Let's stick to fixed low friction sphere for simplicity or create a continuous joint.
       Let's use fixed for now but set friction low in gazebo tag.
  -->
  <gazebo reference="caster_wheel">
    <mu1>0.001</mu1>
    <mu2>0.001</mu2>
  </gazebo>

  <!-- Lidar -->
  <xacro:lidar_sensor parent_link="base_link" x_offset="${chassis_length/2 - 0.05}" z_offset="${chassis_height + 0.02}"/>

  <!-- Gazebo Control -->
  <xacro:diff_drive_controller wheel_separation="${wheel_separation}" wheel_radius="${wheel_radius}"/>

</robot>
